BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040
MCU = RP2040
BOOTLOADER = rp2040
RGBLIGHT_ENABLE = no

WPM_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
OS_DETECTION_ENABLE = yes

I2C_DRIVER = vendor
I2C_DRIVER_REQUIRED = yes
# OLED_ENABLE     = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
POINTING_DEVICE_MODES_ENABLE = no
