OLED_ENABLE     = yes
RGBLIGHT_ENABLE = no
WPM_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_MODES_ENABLE = yes
